import type { Metadata } from "next";
import Header from "@/components/server/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <section className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1 py-16 px-4 sm:px-8 md:px-12 lg:px-20 flex flex-col justify-center items-center">{children}</main>
        </section>
      </body>
    </html>
  );
}
